"""add label to rule_edges

Revision ID: d79f8c97dd43
Revises: 5fd725565ab9
Create Date: 2026-03-01 21:35:06.312081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79f8c97dd43'
down_revision: Union[str, Sequence[str], None] = '5fd725565ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_edges', sa.Column('label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_edges', 'label')
    # ### end Alembic commands ###
